### ISSUE TITLE
vscode theme unreadable after update.

### ISSUE THREAD

**Issue by Strifewind** [thonymg/vscode-darkplusix#1]
After the vscode update to 1.9.0 it seems that the theme has changed the color of atoms, variables, functions and a few other things. I have attempted to reload vscode, uninstall the theme and reload code. Any other suggestions would be appreciated, I really enjoy the darkplusix theme and would enjoy its continued update.

**Comment by thonymg** [comment]
Thanks for support, 
i open an issues on VS-Code for more information about that change in the last update in VS code.
 
i work on it.
