### ISSUE TITLE
Update to latest VS Code changes background to red

### ISSUE THREAD

**Issue by silviurosu** [thonymg/vscode-darkplusix#2]
<img width="793" alt="screenshot 2017-09-11 10 36 34" src="https://user-images.githubusercontent.com/509403/30263326-2b311022-96dd-11e7-8608-a3d12f942d29.png">

Darkplusix 1.1.2
VsCode 1.16.0

**Comment by thonymg** [comment]
Thanks, 
i work on it, but now i hase some internet connexion issues (i'm in Africa)

**Comment by stefanjarina** [comment]
Hi, sent you pull request for this issue.

**Comment by Strifewind** [comment]
Im not seeing a change since the pr was closed. Was this issue resolved?

**Comment by stefanjarina** [comment]
Hi, yes. It is resolved in 1.1.3

**Comment by stefanjarina** [comment]
Hmm, yes, it seems that there is no new version with this fix.
One way to get this fix until new version is released.
Go to `.vscode/extensions/thonymg.darkplusix-1.1.2`
and remove `"background": "",` in  `themes/darkplusix.json` on line 9

**Comment by stefanjarina** [comment]
@thonymg you might want to create new release with the fix :-)
