### ISSUE TITLE
Where do I get a list of Elixir gramar scopes?

### ISSUE THREAD

**Issue by silviurosu** [thonymg/vscode-darkplusix#4]
I see that you used textmate gramar scopes to customize theme.
Where did you got the list of scopes for elixir?
I want to add more colours and I do not know how to target the fields. #

**Comment by thonymg** [comment]
I directly targeted the elements related to syntactic coloring provides this extension
https://github.com/mat-mcloughlin/vscode-elixir

before it was easier hands now VS-code translates the selectors and it is not very clear regarding this translation.

**Comment by silviurosu** [comment]
Thanks.
I figured out how to find the selectors now. I check their regexes: https://github.com/mat-mcloughlin/vscode-elixir/blob/master/syntaxes/elixir.json

Are you planning to add more styling to your extension?
I thinks it needs more colours to atoms, atom based maps, calling methods from modules.
